// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib
{

    public class JsonTrafficSummary
    {

        [JsonProperty("ShapingInfoDetail")]
        public string ShapingInfoDetail { get; set; }

        [JsonProperty("sim-type")]
        public string SimType { get; set; }

        [JsonProperty("response")]
        public Response Response { get; set; }

        [JsonProperty("line-tariffplan")]
        public LineTariffplan LineTariffplan { get; set; }

        [JsonProperty("line-options")]
        public LineOption[] LineOptions { get; set; }

        [JsonProperty("shaping-details")]
        public ShapingDetails ShapingDetails { get; set; }

        [JsonProperty("tariff-plans-campain")]
        public object TariffPlansCampain { get; set; }

        [JsonProperty("options-campain")]
        public object OptionsCampain { get; set; }

        [JsonProperty("promos-campain")]
        public object PromosCampain { get; set; }

        [JsonProperty("line-promos")]
        public LinePromo[] LinePromos { get; set; }

        [JsonProperty("credit-balance-value")]
        public string CreditBalanceValue { get; set; }
    }

}
