// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib
{

    public class Session
    {

        [JsonProperty("expires")]
        public string Expires { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public class Line
    {

        [JsonProperty("contract-code")]
        public string ContractCode { get; set; }

        [JsonProperty("msisdn")]
        public string Msisdn { get; set; }

        [JsonProperty("payment-type")]
        public string PaymentType { get; set; }

        [JsonProperty("rowid")]
        public string Rowid { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("line-type")]
        public string LineType { get; set; }
    }

    public class Login
    {

        [JsonProperty("session")]
        public Session Session { get; set; }

        [JsonProperty("lines")]
        public Line[] Lines { get; set; }
    }

    public class JsonLogin
    {

        [JsonProperty("customer-code")]
        public string CustomerCode { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("response")]
        public Response Response { get; set; }

        [JsonProperty("login")]
        public Login Login { get; set; }
    }

}
