// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib
{

    public class LinePromo
    {

        [JsonProperty("activation-date")]
        public string ActivationDate { get; set; }

        [JsonProperty("buttons")]
        public object Buttons { get; set; }

        [JsonProperty("option-code")]
        public string OptionCode { get; set; }

        [JsonProperty("deactivation-date")]
        public string DeactivationDate { get; set; }

        [JsonProperty("option-name")]
        public string OptionName { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

}
