// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib
{

    public class ShapingDetails
    {

        [JsonProperty("perc-vol-tot")]
        public string PercVolTot { get; set; }

        [JsonProperty("customer-type")]
        public string CustomerType { get; set; }

        [JsonProperty("date-loading")]
        public string DateLoading { get; set; }

        [JsonProperty("period-end-date")]
        public string PeriodEndDate { get; set; }

        [JsonProperty("period-start-date")]
        public string PeriodStartDate { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("max-data-cdr")]
        public string MaxDataCdr { get; set; }

        [JsonProperty("min-data-cdr")]
        public string MinDataCdr { get; set; }

        [JsonProperty("option-name")]
        public string OptionName { get; set; }

        [JsonProperty("com-threshold")]
        public string ComThreshold { get; set; }

        [JsonProperty("tec-Threshold")]
        public string TecThreshold { get; set; }

        [JsonProperty("vol-down")]
        public string VolDown { get; set; }

        [JsonProperty("vol-tot")]
        public string VolTot { get; set; }

        [JsonProperty("vol-up")]
        public string VolUp { get; set; }
    }

}
