// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib
{

    public class ShapingInfoDetails
    {

        [JsonProperty("speed")]
        public object Speed { get; set; }

        [JsonProperty("threshold")]
        public object Threshold { get; set; }
    }

}
