// <auto-generated />
namespace WindAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PushNotificationNewData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PushNotificationNewData));
        
        string IMigrationMetadata.Id
        {
            get { return "201404051313405_PushNotificationNewData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
