// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib.Scoop
{

    public class Counter
    {

        [JsonProperty("CounterMaxValue")]
        public int CounterMaxValue { get; set; }

        [JsonProperty("CounterType")]
        public string CounterType { get; set; }

        [JsonProperty("CounterValue")]
        public int CounterValue { get; set; }

        [JsonProperty("CounterName")]
        public string CounterName { get; set; }

        [JsonProperty("NextResetDate")]
        public string NextResetDate { get; set; }

        [JsonProperty("CounterResidual")]
        public int CounterResidual { get; set; }

        [JsonProperty("CounterLogic")]
        public string CounterLogic { get; set; }
    }

}
