// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib.Scoop
{

    public class CurrentPromo
    {

        [JsonProperty("RelatedCouter")]
        public int RelatedCouter { get; set; }

        [JsonProperty("Counters")]
        public Counter[] Counters { get; set; }

        [JsonProperty("PromoID")]
        public int PromoID { get; set; }

        [JsonProperty("Note")]
        public string Note { get; set; }

        [JsonProperty("PromoName")]
        public string PromoName { get; set; }

        [JsonProperty("ExpirationDate")]
        public string ExpirationDate { get; set; }

        [JsonProperty("Status")]
        public string Status { get; set; }

        [JsonProperty("DiscountExpirationDate")]
        public string DiscountExpirationDate { get; set; }

        [JsonProperty("Rechargeable")]
        public bool Rechargeable { get; set; }

        [JsonProperty("AppliedFee")]
        public double AppliedFee { get; set; }

        [JsonProperty("RegimeFee")]
        public int RegimeFee { get; set; }

        [JsonProperty("PI_ListID")]
        public string PIListID { get; set; }

        [JsonProperty("ActivationDate")]
        public string ActivationDate { get; set; }

        [JsonProperty("Deactivable")]
        public string Deactivable { get; set; }
    }

}
