// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib.Scoop
{

    public class JsonTrafficSummary
    {

        [JsonProperty("MSISNDs")]
        public MSISND[] MSISNDs { get; set; }

        [JsonProperty("FiscalCode")]
        public string FiscalCode { get; set; }

        [JsonProperty("Common")]
        public Common Common { get; set; }

        [JsonProperty("MailIsVerified")]
        public bool MailIsVerified { get; set; }
    }

}
