// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WindDataLib.Scoop
{

    public class OfferData
    {

        [JsonProperty("AvailablePromos")]
        public AvailablePromo[] AvailablePromos { get; set; }

        [JsonProperty("Common")]
        public Common Common { get; set; }

        [JsonProperty("CurrentPromos")]
        public CurrentPromo[] CurrentPromos { get; set; }
    }

}
