//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindAuth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class H3GStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal H3GStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindAuth.H3GStrings", typeof(H3GStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;v:Envelope xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:d=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:c=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:v=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;v:Header /&gt;&lt;v:Body&gt;&lt;n0:loadInfoRapide id=&quot;o0&quot; c:root=&quot;1&quot; xmlns:n0=&quot;http://inforapide.service.selfcareapi.ericsson.com/&quot;&gt;&lt;msisdn i:type=&quot;d:string&quot;&gt;{0}&lt;/msisdn&gt;&lt;/n0:loadInfoRapide&gt;&lt;/v:Body&gt;&lt;/v:Envelope&gt;.
        /// </summary>
        internal static string InfoRapidService {
            get {
                return ResourceManager.GetString("InfoRapidService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:cred=&quot;http://credential.service.selfcareapi.ericsson.com/&quot;&gt;&lt;soapenv:Header/&gt;&lt;soapenv:Body&gt;&lt;cred:login&gt;&lt;username&gt;{0}&lt;/username&gt;&lt;password&gt;{1}&lt;/password&gt;&lt;userType&gt;MSISDN&lt;/userType&gt;&lt;/cred:login&gt;&lt;/soapenv:Body&gt;&lt;/soapenv:Envelope&gt;.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
    }
}
